### ISSUE TITLE
BAR offset ignored

### ISSUE THREAD

**Issue by victorkemp** [MYSTRANsolver/MYSTRAN#42]
Version 15.1.6
In this example, the offset should double the length of the beam, halving its stiffness and doubling its displacement.

```
SOL 101
CEND
SUBCASE 1
    DISPLACEMENT(PLOT,PRINT) = ALL
    LOAD = 1
    SPC = 2
BEGIN BULK
PARAM       POST      -1
GRID           1              0.      0.      0.
GRID           2              1.      0.      0.
CBAR           1       1       1       2      0.      1.      0.             +C1
+C1                         -0.5      0.      0.     0.5      0.      0.
PBARL          1       1             BAR
              .1      .1      0.
MAT1           1   1.+11              0.
FORCE          1       2              1.  30000.      0.      0.
SPC            2       1  123456
ENDDATA
```

But the solution is

```
                                              (in global coordinate system at each grid)
           GRID     COORD      T1            T2            T3            R1            R2            R3
                     SYS
              1        0  0.0           0.0           0.0           0.0           0.0           0.0         
              2        0  3.000000E-05  0.0           0.0           0.0           0.0           0.0         
```

Displacement of 3e-5 is what you'd get from the original length (1.0), not the doubled length (2.0) according to u = FL/(EA).

**Comment by JuanP74** [comment]
Only when offset leads to an increased length the offset fails; it was intended to support only offsets in the cross-section plane which is the usual modeling approach, however it is not mentioned in the user manual and it's supported by commercial nastrans (even by Nasa95 cosmic nastran). In the example attached, offsets defined in a different coordinate 
frame than the basic, but that not increase bar length, are treated properly. 
[cbar_T_para_offset_1_my.zip](https://github.com/MYSTRANsolver/MYSTRAN/files/14971464/cbar_T_para_offset_1_my.zip)

**Comment by victorkemp** [comment]
I should have updated this but it turns out offset causing a length change does work OK. The problem is that the continuation label +C1 isn't correctly aligned at the start of field 10 which caused Mystran to silently ignore the continuation line with the offset data.

**Comment by JuanP74** [comment]
Ah, ok, I noticed the issue but forgot updating the mystran file, sorry.

**Comment by SteveDoyle2** [comment]
The result I got matches Juan's of ![image](https://github.com/MYSTRANsolver/MYSTRAN/assets/1059417/2f12642a-cdfc-488d-bead-a7ef0de2fa7f)

I also made separate tests of just doubling the length of the bar using offsets.  It's working
