### ISSUE TITLE
double writing of PCOMP note in CTRIA3/CQUAD4 Stress table

### ISSUE THREAD

**Issue by SteveDoyle2** [MYSTRANsolver/MYSTRAN#52]
![image](https://github.com/MYSTRANsolver/MYSTRAN/assets/1059417/0c525316-6dc3-4572-b8f5-f0683cf83a44)
[cquad4_pcomp_center.txt](https://github.com/MYSTRANsolver/MYSTRAN/files/14764293/cquad4_pcomp_center.txt)

**Comment by SteveDoyle2** [comment]
The ans file doesn't show the note, so presumably that was intended for the ANS file.

**Comment by zchlrnr** [comment]
I just saw that this could be closed by the PR from yesterday, looks snazzy
