### ISSUE TITLE
Bug in LOADB.f90

### ISSUE THREAD

**Issue by galbramc** [MYSTRANsolver/MYSTRAN#81]
Line 216 of LOADB.f90 reads into CARD1 when it should read into CARD2.

**Comment by zchlrnr** [comment]
@SteveDoyle2 is there any chance this is rectified by the patch you were working on?

**Comment by SteveDoyle2** [comment]
I think it’s done, but needs Bruno’s testing. He’s got more cases than I do.

**Comment by SteveDoyle2** [comment]
closed with latest version
